# Generated by Django 5.0 on 2024-03-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_response',
            field=models.IntegerField(default=1),
        ),
    ]
