# Generated by Django 5.0 on 2024-03-14 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_current_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.studentresponse'),
        ),
    ]
