# Generated by Django 5.0 on 2024-03-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_current_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertresponse',
            name='current_response',
        ),
        migrations.AddField(
            model_name='expertresponse',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='expertresponse',
            name='confidence',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='expertresponse',
            name='knowledge',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='expertresponse',
            name='sentence',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='expertresponse',
            name='strength',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='expertresponse',
            name='username',
            field=models.TextField(default=''),
        ),
    ]
