# Generated by Django 5.0 on 2024-05-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_expertresponse_current_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='expert_responses',
            field=models.ManyToManyField(blank=True, to='app.expertresponse'),
        ),
    ]
