# Generated by Django 5.0 on 2024-05-08 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_studentresponse_expert_responses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertresponse',
            name='username',
        ),
        migrations.AddField(
            model_name='expertresponse',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
